test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# Use bin/rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
amazon:
  service: S3
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region: <%= ENV['AWS_REGION'] %>
  bucket: <%= ENV['AWS_BUCKET_NAME'] %>

amazon_transfer:
  service: S3
  access_key_id: <%= ENV['TRANSFER_AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['TRANSFER_AWS_SECRET_ACCESS_KEY'] %>
  region: <%= ENV['TRANSFER_AWS_REGION'] %>
  bucket: <%= ENV['TRANSFER_AWS_BUCKET_NAME'] %>

s3compatible:
  service: S3
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  bucket: <%= ENV['AWS_BUCKET_NAME'] %>
  endpoint: <%= ENV['S3_ENDPOINT'] %>
  force_path_style: <%= ENV['S3_FORCE_PATH_STYLE'] %>

s3compatible_transfer:
  service: S3
  access_key_id: <%= ENV['TRANSFER_AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['TRANSFER_AWS_SECRET_ACCESS_KEY'] %>
  bucket: <%= ENV['TRANSFER_AWS_BUCKET_NAME'] %>
  endpoint: <%= ENV['TRANSFER_S3_ENDPOINT'] %>
  force_path_style: <%= ENV['S3_FORCE_PATH_STYLE'] %>

# Remember not to checkin your GCS keyfile to a repository
# google:
#   service: GCS
#   project: your_project
#   credentials: <%= Rails.root.join("path/to/gcs.keyfile") %>
#   bucket: your_own_bucket-<%= Rails.env %>

# Use bin/rails credentials:edit to set the Azure Storage secret (as azure_storage:storage_access_key)
# microsoft:
#   service: AzureStorage
#   storage_account_name: your_account_name
#   storage_access_key: <%= Rails.application.credentials.dig(:azure_storage, :storage_access_key) %>
#   container: your_container_name-<%= Rails.env %>

# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ amazon, google, microsoft ]
